// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlnjfXs75GWF7iJsaNqDQ-3W0se4sJuOk',
    appId: '1:54077752195:web:2ce5daf16022e5d3b52cb6',
    messagingSenderId: '54077752195',
    projectId: 'flutter-firestore-f4ef8',
    authDomain: 'flutter-firestore-f4ef8.firebaseapp.com',
    storageBucket: 'flutter-firestore-f4ef8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3bnalXbPRVUmfdGf0GB8EjEYeJ_jNAV0',
    appId: '1:54077752195:android:2220c7d492832724b52cb6',
    messagingSenderId: '54077752195',
    projectId: 'flutter-firestore-f4ef8',
    storageBucket: 'flutter-firestore-f4ef8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAunPMbZF9ztJ84-iOXxzFKqQec7eraDZ8',
    appId: '1:54077752195:ios:da86f6e035580076b52cb6',
    messagingSenderId: '54077752195',
    projectId: 'flutter-firestore-f4ef8',
    storageBucket: 'flutter-firestore-f4ef8.appspot.com',
    iosBundleId: 'com.example.flutterFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAunPMbZF9ztJ84-iOXxzFKqQec7eraDZ8',
    appId: '1:54077752195:ios:8d18e4a637f7895cb52cb6',
    messagingSenderId: '54077752195',
    projectId: 'flutter-firestore-f4ef8',
    storageBucket: 'flutter-firestore-f4ef8.appspot.com',
    iosBundleId: 'com.example.flutterFirestore.RunnerTests',
  );
}
