// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5pI1UQvHdsAC0Gkj5nbwgBl9xmW42c80',
    appId: '1:147012924022:web:89c6a134f2ab1ca518a557',
    messagingSenderId: '147012924022',
    projectId: 'fir-flutter-codelab-ef3aa',
    authDomain: 'fir-flutter-codelab-ef3aa.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ef3aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX4Tnrzgt3-w4OweMDvAgdm2n65oiGt7w',
    appId: '1:147012924022:android:a4484bd004c4c10e18a557',
    messagingSenderId: '147012924022',
    projectId: 'fir-flutter-codelab-ef3aa',
    storageBucket: 'fir-flutter-codelab-ef3aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfeA28vNtux49Tpqwgl49wLfB-LZtnKu0',
    appId: '1:147012924022:ios:c1fbd97652346a8418a557',
    messagingSenderId: '147012924022',
    projectId: 'fir-flutter-codelab-ef3aa',
    storageBucket: 'fir-flutter-codelab-ef3aa.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfeA28vNtux49Tpqwgl49wLfB-LZtnKu0',
    appId: '1:147012924022:ios:94d0ab7b9134c1cc18a557',
    messagingSenderId: '147012924022',
    projectId: 'fir-flutter-codelab-ef3aa',
    storageBucket: 'fir-flutter-codelab-ef3aa.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
