// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFd1GZDGcmqkDgu63dRP3HJ6IN5OU0cBU',
    appId: '1:286459103273:web:72cc3b5e9a2bc5409bf438',
    messagingSenderId: '286459103273',
    projectId: 'fir-flutter-codelab-41f64',
    authDomain: 'fir-flutter-codelab-41f64.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-41f64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV4LXdUrq2ZG2Ml7jpnKLqgJiMPo2BauY',
    appId: '1:286459103273:android:7609695ec091c2079bf438',
    messagingSenderId: '286459103273',
    projectId: 'fir-flutter-codelab-41f64',
    storageBucket: 'fir-flutter-codelab-41f64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8vWPW2gmfinZZyNiYngyoMsrsvoOxO1c',
    appId: '1:286459103273:ios:df08939d53cd346a9bf438',
    messagingSenderId: '286459103273',
    projectId: 'fir-flutter-codelab-41f64',
    storageBucket: 'fir-flutter-codelab-41f64.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8vWPW2gmfinZZyNiYngyoMsrsvoOxO1c',
    appId: '1:286459103273:ios:0cfa1706fd6d73879bf438',
    messagingSenderId: '286459103273',
    projectId: 'fir-flutter-codelab-41f64',
    storageBucket: 'fir-flutter-codelab-41f64.appspot.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
